org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.parallel=true
mod_version=0.1.0
maven_group=io.github.linlunaire
minecraft_version=26.2
fabric_loader_version=0.19.3
neoforge_version=26.2.0.75
kotlin_runtime_version=2.4.0
fabric_kotlin_version=1.13.14+kotlin.2.4.20
kotlin_for_forge_version=6.3.0
