license = "MIT AND Apache-2.0"

[[mods]]
modId = "transit_core"
version = "${version}"
displayName = "Kotlin LunaCore"
authors = "linlunaire"
description = "A next-generation Kotlin foundation for the Minecraft mod ecosystem."

[[dependencies.transit_core]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.75,26.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.transit_core]]
modId = "minecraft"
type = "required"
versionRange = "[26.2]"
ordering = "NONE"
side = "BOTH"
