license = "LGPL-3.0-or-later"

[[mods]]
modId = "transit_core"
version = "${version}"
displayName = "Kotlin LunaCore"
authors = "linlunaire"
description = "A shared Kotlin runtime and small JVM utilities for Minecraft mods."

[[dependencies.transit_core]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.75,26.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.transit_core]]
modId = "minecraft"
type = "required"
versionRange = "[26.2]"
ordering = "NONE"
side = "BOTH"
